In [9]:
import pandas as pd
import geopandas as gpd
from shapely import LineString

In [10]:
pd.set_option('display.width', 500)
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', 500)

In [11]:
point_df = pd.read_excel('sample-folder/trial-calculate-line-distance.xlsx')

In [12]:
point_df

      SiteID_Source_Alternative  Longitude_Source  Latitude_Source SiteID_Target_Alternative  Longitude_Target  Latitude_Target    distance
0                      SiteID-1        106.041358        -6.003581               SiteID-3698        106.043200        -6.006975  431.734531
1                      SiteID-2        106.042389        -6.009056               SiteID-3698        106.043200        -6.006975  249.776735
2                      SiteID-3        106.069482        -6.025184              SiteID-15302        106.071811        -6.026569  302.117152
3                      SiteID-4        106.044056        -6.015861               SiteID-4526        106.046111        -6.013611  340.277799
4                      SiteID-5        106.049439        -6.013789               SiteID-4526        106.046111        -6.013611  370.980627
...                         ...               ...              ...                       ...               ...              ...         ...
15299              SiteID-15300        106.065819        -6.046281              SiteID-15299        106.069061        -6.043261  494.435046
15300              SiteID-15301        106.075556        -6.037694              SiteID-15297        106.074100        -6.040900  393.719346
15301              SiteID-15302        106.071811        -6.026569                  SiteID-3        106.069482        -6.025184  302.117152
15302              SiteID-15303        105.883292        -6.107036              SiteID-15304        105.881914        -6.105358  242.498344
15303              SiteID-15304        105.881914        -6.105358              SiteID-15303        105.883292        -6.107036  242.498344

[15304 rows x 7 columns]

In [13]:
point_df['linestring'] = "LINESTRING (" + point_df['Longitude_Source'].astype(str) + " " + point_df['Latitude_Source'].astype(str) + ", " + point_df['Longitude_Target'].astype(str) + " " + point_df['Latitude_Target'].astype(str) + ")"

In [17]:
point_df.to_csv('result/ISD-with_linestring.csv', index=False)