In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np

In [2]:
# pd.set_option('display.width', 500)
# pd.set_option('display.max_rows', 50)
# pd.set_option('display.max_columns', 500)
# pd.set_option('display.max_colwidth', 500)

In [3]:
cellrebel = pd.read_csv('rsrp_cell_rebel.csv')
kabupaten = gpd.read_file('Polygon Kecamatan_Fajar/Kab_Kec_Combined_June_2021V1.TAB')

In [4]:
pd_to_gpd = gpd.GeoDataFrame(cellrebel, geometry=gpd.points_from_xy(cellrebel.longitude, cellrebel.latitude), crs=4326)

In [5]:
pd_to_gpd.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [6]:
kabupaten.crs

<Geographic 2D CRS: GEOGCS["unnamed",DATUM["MIF 0",SPHEROID["WGS 84 (M ...>
Name: unnamed
Axis Info [ellipsoidal]:
- lat[north]: Latitude (degree)
- lon[east]: Longitude (degree)
Area of Use:
- undefined
Datum: MIF 0
- Ellipsoid: WGS 84 (MAPINFO Datum 0)
- Prime Meridian: Greenwich

In [7]:
# pd_to_gpd = pd_to_gpd.within(karawang)
# pd_to_gpd['test'] = pd_to_gpd.sjoin(karawang, how="inner", predicate='within')
points_within = pd_to_gpd.sjoin(kabupaten, how='inner', predicate='within')

/home/nivag/2023/2023 XL - Prophet Model Forecasting/.env/lib/python3.10/site-packages/geopandas/geodataframe.py:2061: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: GEOGCS["unnamed",DATUM["MIF 0",SPHEROID["WGS 84 (M ...

  return geopandas.sjoin(left_df=self, right_df=df, *args, **kwargs)

In [8]:
# feather = pd.DataFrame(points_within.drop(columns='geometry').reset_index())
# feather.to_csv('cellrebel_mapping_30032023.csv', index=False)

In [9]:
points_within = points_within[~points_within['reference_signal_received_power'].isnull()]

In [10]:
points_within

,kabupaten,mobile_operator,longitude,latitude,quadkey_17,created_date,reference_signal_received_power,absolute_rf_channel_number,geometry,index_right,No_kec,Kab_kec,No_kabkota,Kab_kot,Prop,Prov,Pndd,Poc,Prov_Kab_Kec
0,Kota Jakarta Utara,Telkomsel,106.897778,-6.150245,31001300022001022,2023-03-27 07:32:00.373,-93.0,2.510000e+02,POINT (106.89778 -6.15024),447,050,KELAPA GADING,75,JAKARTA UTARA,31,DKI JAKARTA,54377.0,JAKARTA,DKI JAKARTA_JAKARTA UTARA_KELAPA GADING
726,Kota Jakarta Utara,Indosat Ooredoo,106.903322,-6.173721,31001300022003210,2023-03-26 14:46:00.230,-122.0,1.481000e+03,POINT (106.90332 -6.17372),447,050,KELAPA GADING,75,JAKARTA UTARA,31,DKI JAKARTA,54377.0,JAKARTA,DKI JAKARTA_JAKARTA UTARA_KELAPA GADING
988,Kota Jakarta Utara,Indosat Ooredoo,106.909177,-6.164242,31001300022003100,2023-03-26 10:58:00.097,-121.0,2.147484e+09,POINT (106.90918 -6.16424),447,050,KELAPA GADING,75,JAKARTA UTARA,31,DKI JAKARTA,54377.0,JAKARTA,DKI JAKARTA_JAKARTA UTARA_KELAPA GADING
989,Kota Jakarta Utara,Indosat Ooredoo,106.909177,-6.164242,31001300022003100,2023-03-26 10:58:00.097,-125.0,2.147484e+09,POINT (106.90918 -6.16424),447,050,KELAPA GADING,75,JAKARTA UTARA,31,DKI JAKARTA,54377.0,JAKARTA,DKI JAKARTA_JAKARTA UTARA_KELAPA GADING
990,Kota Jakarta Utara,Indosat Ooredoo,106.909177,-6.164242,31001300022003100,2023-03-26 10:58:00.097,-125.0,2.147484e+09,POINT (106.90918 -6.16424),447,050,KELAPA GADING,75,JAKARTA UTARA,31,DKI JAKARTA,54377.0,JAKARTA,DKI JAKARTA_JAKARTA UTARA_KELAPA GADING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680342,Bogor,Indosat Ooredoo,106.576905,-6.339851,31001211310012011,2023-03-27 13:02:00.626,-91.0,2.000000e+02,POINT (106.57691 -6.33985),199,070,PAGEDANGAN,03,TANGERANG,36,BANTEN,8029.0,JAKARTA,BANTEN_TANGERANG_PAGEDANGAN
689279,Bogor,Indosat Ooredoo,106.576979,-6.339826,31001211310012011,2023-03-27 13:02:00.627,-86.0,2.000000e+02,POINT (106.57698 -6.33983),199,070,PAGEDANGAN,03,TANGERANG,36,BANTEN,8029.0,JAKARTA,BANTEN_TANGERANG_PAGEDANGAN
722168,Bogor,Indosat Ooredoo,106.576908,-6.339849,31001211310012011,2023-03-27 13:02:00.627,-86.0,2.000000e+02,POINT (106.57691 -6.33985),199,070,PAGEDANGAN,03,TANGERANG,36,BANTEN,8029.0,JAKARTA,BANTEN_TANGERANG_PAGEDANGAN
722169,Bogor,Indosat Ooredoo,106.576905,-6.339851,31001211310012011,2023-03-27 13:02:00.627,-86.0,2.000000e+02,POINT (106.57691 -6.33985),199,070,PAGEDANGAN,03,TANGERANG,36,BANTEN,8029.0,JAKARTA,BANTEN_TANGERANG_PAGEDANGAN
722170,Bogor,Indosat Ooredoo,106.576924,-6.339850,31001211310012011,2023-03-27 13:02:00.545,-86.0,2.000000e+02,POINT (106.57692 -6.33985),199,070,PAGEDANGAN,03,TANGERANG,36,BANTEN,8029.0,JAKARTA,BANTEN_TANGERANG_PAGEDANGAN

In [11]:
pivot = pd.pivot_table(points_within , index= ['Prov_Kab_Kec', 'kabupaten'],
                        columns=['mobile_operator'], values=['reference_signal_received_power'],aggfunc = np.mean)

In [12]:
pivot.reset_index(inplace=True, col_level=1, allow_duplicates=False)

In [13]:
pivot = pivot.droplevel(level=0, axis=1)

In [14]:
pivot

mobile_operator,Prov_Kab_Kec,kabupaten,3,Indosat Ooredoo,Smartfren,Telkomsel,XL Axiata
0,BANTEN_KOTA TANGERANG SELATAN_SETU,Bogor,NaN,NaN,NaN,-99.795455,NaN
1,BANTEN_LEBAK_CURUG BITUNG,Bogor,NaN,-98.714286,-93.000000,NaN,NaN
2,BANTEN_LEBAK_MAJA,Bogor,NaN,-115.300000,NaN,NaN,NaN
3,BANTEN_TANGERANG_CISAUK,Bogor,NaN,-104.000000,-102.722222,-93.000000,NaN
4,BANTEN_TANGERANG_JAMBE,Bogor,NaN,-95.774194,NaN,-100.192308,NaN
...,...,...,...,...,...,...,...
206,JAWA BARAT_SUKABUMI_SUKARAJA,Sukabumi,-108.726667,-100.731933,-105.375000,-106.060784,-102.297619
207,JAWA BARAT_SUKABUMI_SURADE,Sukabumi,NaN,-102.047344,NaN,-110.319588,-107.618182
208,JAWA BARAT_SUKABUMI_TEGAL BULEUD,Sukabumi,NaN,-105.567010,NaN,-118.454545,-100.309524
209,JAWA BARAT_SUKABUMI_WALURAN,Sukabumi,NaN,-108.000000,NaN,-121.500000,-105.333333
210,JAWA BARAT_SUKABUMI_WARUNG KIARA,Sukabumi,NaN,-104.932432,-100.779343,-98.888889,-94.057143

In [15]:
test = pivot.merge(kabupaten[['Prov_Kab_Kec', 'geometry']], how='left', on='Prov_Kab_Kec')

In [16]:
test1 = gpd.GeoDataFrame(test, geometry='geometry', crs=4326)

In [17]:
test1.to_csv('pivot_cellrebel_maret2023.csv', index=False)