In [1]:
import pandas as pd
import geopandas as gpd
import os

In [2]:
boundary = gpd.read_file('Polygon/Kecamatan_Jabotabek.TAB')
boundary = boundary.to_crs(4326)

In [3]:
dir_path = 'CR_Data/'
csv_files = [f for f in os.listdir(dir_path) if f.endswith('.csv')]
cellrebel_consolidate = pd.DataFrame()
boundary['geometry1'] = boundary['geometry'].astype(str)

for file in csv_files:
    
    csv_path = os.path.join(dir_path, file)
    cellrebel = pd.read_csv(csv_path)
    cellrebel = cellrebel[~cellrebel['reference_signal_received_power'].isnull()]
    cellrebel = cellrebel[cellrebel['province'].str.contains('Banten')]

    cellrebel = gpd.GeoDataFrame(cellrebel, geometry=gpd.points_from_xy(cellrebel.longitude, cellrebel.latitude), crs=4326)
    cellrebel = gpd.sjoin(left_df= cellrebel, right_df=boundary, how='left', predicate='within')

    cellrebel.drop(cellrebel.iloc[:,8:21],axis=1, inplace=True)
    cellrebel.drop(cellrebel.iloc[:,2:7],axis=1, inplace=True)
    
    cellrebel = cellrebel[~cellrebel['geometry1'].isnull()]
    # cellrebel.fillna(0, inplace=True)
    cellrebel_consolidate = pd.concat([cellrebel, cellrebel_consolidate], ignore_index=True)

In [4]:
cellrebel_consolidate['geometry1'] = cellrebel_consolidate['geometry1'].astype(str)

In [5]:
cellrebel_consolidate

,Unnamed: 0,mobile_operator,reference_signal_received_power,geometry1
0,42227,XL Axiata,-72.0,"POLYGON ((106.756523 -6.262475, 106.756478 -6...."
1,42228,XL Axiata,-90.0,"POLYGON ((106.694198 -6.230165, 106.694118 -6...."
2,42229,XL Axiata,-88.0,"POLYGON ((106.779902 -6.316532, 106.779869 -6...."
3,42230,Telkomsel,-108.0,"POLYGON ((106.75901 -6.32835, 106.75896 -6.328..."
4,42231,PT Telekomunikasi Indonesia,-93.0,"POLYGON ((106.756523 -6.262475, 106.756478 -6...."
...,...,...,...,...
1778186,43230,Telkomsel,-106.0,"POLYGON ((106.19938 -6.102085, 106.19932 -6.10..."
1778187,43231,Telkomsel,-92.0,"POLYGON ((106.212379 -6.104174, 106.212 -6.104..."
1778188,43232,PT Telekomunikasi Indonesia,-102.0,"POLYGON ((106.14818 -6.09505, 106.1478 -6.0944..."
1778189,43233,Telkomsel,-93.0,"POLYGON ((106.212379 -6.104174, 106.212 -6.104..."
1778190,43234,PT Telekomunikasi Indonesia,-118.0,"POLYGON ((106.14818 -6.09505, 106.1478 -6.0944..."